install:
  - cinst pester
platform: Any CPU
build: false

test_script:
  - ps: $res = Invoke-Pester -Script @{ Path = ".\"; Arguments = 'Cloudbuild'} -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

deploy_script:
  - ps: if ($res.FailedCount -eq 0) { 
      write-host "All Tests succeeded, deploying CAM to Powershell Gallery" ; 
      $Path = (Get-Item -Path ".\").FullName ;
      Install-Module AzureRm;
      $manifest = Get-Content -Raw -Path "$Path\CAM.psd1" ;
      $manifest -replace "ModuleVersion = '0.0.1'" , "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'" | Out-File "$Path\CAM.psd1";
      New-Directory -Item directory -Path "$Path\publish";
      Copy-Item "$Path\CAM.psd1" -Destination "$Path\publish";
      Copy-Item "$Path\CAM.psm1" -Destination "$Path\publish";
      Copy-Item "$Path\CAM.tests.ps1" -Destination "$Path\publish";
      Copy-Item "$Path\PSScriptAnalyzerSettings.psd1" -Destination "$Path\publish";
      Copy-Item "$Path\LICENSE" -Destination "$Path\publish";
      Publish-Module -Path "$Path\publish" -NuGetApiKey $env:NugetKey;
      write-host "Published module with version $env:APPVEYOR_BUILD_VERSION"}
