install:
  - cinst pester
platform: Any CPU
build: false

test_script:
  - ps: $res = Invoke-Pester -Script @{ Path = ".\"; Arguments = 'Cloudbuild'} -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

deploy_script:
  - ps: if ($res.FailedCount -eq 0) { write-host "All Tests succeeded, deploying CAM to Powershell Gallery" ; Publish-Module -Name "CAM" -NuGetApiKey $env:NugetKey }
